/**
 * Engineering Design Report PDF Export Utility using jsPDF.
 */

import { jsPDF } from 'jspdf';
import { SavedDesign, ExtractedRequirements } from '../types';

export function exportDesignToPdf(design: SavedDesign) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 18;

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 24, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('ENGINEERING SPECIFICATION & SIZING REPORT', 14, 12);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('LOW-VOLTAGE MOTOR-STARTER PANEL DESIGN ASSISTANT', 14, 18);
  doc.text(`DESIGN ID: ${design.id}  |  CATALOG: v${design.catalog_version}  |  RULES: v${design.rule_version}`, pageWidth - 14, 18, { align: 'right' });

  y = 32;

  // Disclaimer Box (Statutory Engineering Warning)
  doc.setFillColor(254, 242, 242); // red-50
  doc.setDrawColor(239, 68, 68); // red-500
  doc.setLineWidth(0.5);
  doc.rect(14, y, pageWidth - 28, 14, 'FD');

  doc.setTextColor(185, 28, 28); // red-700
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('MANDATORY SAFETY & COMPLIANCE DIRECTIVE:', 18, y + 5);
  doc.setFont('helvetica', 'normal');
  doc.text('This document was generated by an AI engineering assistance system. It does not replace qualified engineering review.', 18, y + 9);
  doc.text('All electrical equipment must be verified by a qualified Professional Engineer (PE) prior to manufacture or installation.', 18, y + 12);

  y += 20;

  // Project Info Table
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Design Identification & Raw Brief', 14, y);
  y += 5;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Title: ${design.title}`, 14, y);
  doc.text(`Created: ${new Date(design.created_at).toLocaleString()}`, 110, y);
  y += 4;
  doc.text(`Status: ${design.status}`, 14, y);
  doc.text(`Overall Compliance: ${design.compliance?.overall_status || 'DRAFT'}`, 110, y);
  y += 5;

  doc.setFont('helvetica', 'italic');
  const briefLines = doc.splitTextToSize(`Brief: "${design.raw_brief}"`, pageWidth - 28);
  doc.text(briefLines, 14, y);
  y += (briefLines.length * 4) + 4;

  // Requirements Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2. Electrical Specifications (Structured Requirements)', 14, y);
  y += 5;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  const req = (design.requirements || {}) as Partial<ExtractedRequirements>;
  doc.text(`• Motor Shaft Power: ${req.motor_power_kw || 'N/A'} kW`, 16, y);
  doc.text(`• Nominal Voltage: ${req.voltage_v || 415} V AC, ${req.phase || 3}-Phase, ${req.frequency_hz || 50} Hz`, 100, y);
  y += 4;
  doc.text(`• Full-Load Current (FLC): ${req.motor_current_a || 'N/A'} A`, 16, y);
  doc.text(`• Starting Method: ${req.starter_type || 'DOL'}`, 100, y);
  y += 4;
  doc.text(`• Branch Protection Required: ${req.protection_required ? 'Yes (MPCB/MCCB)' : 'No'}`, 16, y);
  doc.text(`• Overload Protection Required: ${req.overload_protection_required ? 'Yes (Class 10A)' : 'No'}`, 100, y);
  y += 7;

  // Deterministic Sizing Calculations Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('3. Deterministic Sizing Calculations', 14, y);
  y += 5;

  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 6, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.text('ID', 16, y + 4);
  doc.text('CALCULATION NAME', 32, y + 4);
  doc.text('FORMULA IDENTIFIER', 85, y + 4);
  doc.text('RESULT', 145, y + 4);
  doc.text('STATUS', 178, y + 4);
  y += 7;

  doc.setFont('helvetica', 'normal');
  (design.calculations || []).forEach((c) => {
    doc.text(c.calculation_id, 16, y);
    doc.text(c.name.slice(0, 26), 32, y);
    doc.text(c.formula_id.slice(0, 32), 85, y);
    doc.text(`${c.result_value} ${c.result_unit}`, 145, y);
    doc.text(c.status, 178, y);
    y += 4.5;
  });
  y += 4;

  // Bill of Materials (BOM) Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('4. Bill of Materials (Catalog-Constrained Components)', 14, y);
  y += 5;

  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 6, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.text('CAT ID', 16, y + 4);
  doc.text('TYPE', 40, y + 4);
  doc.text('MODEL / SPECS', 80, y + 4);
  doc.text('RATED', 145, y + 4);
  doc.text('VERSION', 175, y + 4);
  y += 7;

  doc.setFont('helvetica', 'normal');
  (design.components || []).slice(0, 7).forEach((comp) => {
    doc.text(comp.component_id, 16, y);
    doc.text(comp.component_type.slice(0, 18), 40, y);
    doc.text(`${comp.manufacturer} ${comp.model}`.slice(0, 32), 80, y);
    const ratingStr = comp.rated_current ? `${comp.rated_current} A` : (comp.overload_range_min ? `${comp.overload_range_min}-${comp.overload_range_max} A` : '-');
    doc.text(ratingStr, 145, y);
    doc.text(`v${comp.catalog_version}`, 175, y);
    y += 4.5;
  });
  y += 4;

  // Compliance Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(`5. Compliance Rule Verification (Rule Set v${design.rule_version})`, 14, y);
  y += 5;

  (design.compliance?.rule_results || []).slice(0, 6).forEach((r) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    const passColor = r.result === 'PASS' ? [22, 101, 52] : [185, 28, 28];
    doc.setTextColor(passColor[0], passColor[1], passColor[2]);
    doc.text(`[${r.result}] ${r.rule_id}: ${r.title}`, 16, y);

    doc.setTextColor(71, 85, 105);
    doc.setFont('helvetica', 'normal');
    doc.text(`Ref: ${r.source_reference}`, 110, y);
    y += 4;
  });

  y += 4;

  // Page 2 or Bottom Approval Block
  if (y > 230) {
    doc.addPage();
    y = 20;
  }

  // Engineer Sign-Off Block
  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(0.7);
  doc.setFillColor(248, 250, 252);
  doc.rect(14, y, pageWidth - 28, 38, 'FD');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('ENGINEERING APPROVAL SIGN-OFF & GOVERNANCE', 18, y + 6);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  if (design.approval && design.approval.approval_status === 'APPROVED') {
    doc.text(`Approved By: ${design.approval.engineer_name}`, 18, y + 13);
    doc.text(`Timestamp: ${new Date(design.approval.timestamp).toLocaleString()}`, 110, y + 13);
    doc.text(`Comments: ${design.approval.comments}`, 18, y + 19);
    doc.setFont('courier', 'normal');
    doc.setFontSize(6.5);
    doc.text(`Verification SHA-256: ${design.approval.digital_signature_hash}`, 18, y + 26);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(22, 101, 52);
    doc.text('STATUS: FORMALLY APPROVED FOR MOTOR-STARTER BUILD', 18, y + 33);
  } else {
    doc.setTextColor(180, 83, 9); // amber-700
    doc.text('STATUS: PENDING QUALIFIED ENGINEERING REVIEW', 18, y + 14);
    doc.setTextColor(100, 116, 139);
    doc.text('Signature Line: _________________________________________    Date: ______________', 18, y + 25);
  }

  // Save the PDF
  doc.save(`MotorStarter_Design_${design.id}.pdf`);
}
